version: '3'
services:
  mariadb:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    container_name: mariadb
    environment:
      - TZ=Europe/Berlin
    hostname: mariadb
    image: mariadb:latest
    networks:
      ext-ports:
        aliases:
          - mariadb
      backend:
        aliases:
          - mariadb
    ports:
      - 3306:3306/tcp
    restart: always
    volumes:
      - data:/var/lib/mysql
      - conf:/etc/mysql
  
  phpmyadmin:
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    hostname: phpmyadmin
    image: phpmyadmin:latest
    networks:
      www-proxy:
        aliases:
          - phpmyadmin
      backend:
        aliases:
          - phpmyadmin
    restart: unless-stopped

volumes:
  data:
  conf:

networks:
  backend:
    external: true
  www-proxy:
    external: true
  ext-ports:
    external: true