version: '3'
services:
  redm:
    #deploy:
      #resources:
        #limits:
          #cpus: '2'
          #memory: 2G

    container_name: redm
    environment:
      - TZ=Europe/Berlin
      - SRV_ADR=https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/
      - UID=1000
      - GID=1000
      - DATA_DIR=/serverdata
      - SERVER_DIR=/serverdata/serverfiles
      - SERVER_KEY=
      - GAME_CONFIG=
      - MANUAL_UPDATES=true
      - START_VARS=
    hostname: redm
    image: ich777/redmserver:latest
    networks:
      ext-ports:
        aliases:
          - redm
      backend:
        aliases:
          - redm
    ports:
      - 30120:30120/tcp
      - 40120:40120/tcp
      - 30120:30120/udp
    restart: always
    volumes:
      - data:/serverdata/serverfiles

volumes:
  data:

networks:

  ext-ports:
    external: true
  backend:
    external: true