version: '3'

services:
  hbbs:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r hbbr:21117
    volumes:
      - data:/root
    networks:
      ext-ports:
        aliases:
          - hbbs
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - data:/root
    networks:
      ext-ports:
        aliases:
          - hbbr
    restart: unless-stopped
    
volumes:
  data:
  
networks:
  ext-ports:
    external: true