version: '3'
services:
  ytdl:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    container_name: yt-dl
    restart: always
    volumes:
        - data:/downloads
    image: alexta69/metube
    networks:
      www-proxy-internet:
        aliases:
        - yt-dl
            
volumes:
  data:
            
networks:
  www-proxy-internet:
    external: true